"""Added profession to Worker model

Revision ID: 9cc5152422ae
Revises: 
Create Date: 2026-04-30 23:52:18.270945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc5152422ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'profession',
                sa.String(length=100),
                nullable=False,
                server_default='General'
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('profession')

    # ### end Alembic commands ###
